Make prefixes only count non-color characters & General cleanup
Loving11ish/ClansLite pull request #7
Opened 2024-02-12 11:51 UTC by TechnicallyCoded

Prefixes count color codes in the max length which isn't actually displayed to the end-user. Therefore the character limit shouldn't apply to color codes.

2024-02-12 16:14 UTC, Loving11ish requested changes
Can you also change the sender.sendMessage() to player.sendMessage() please?

2024-02-12 16:14 UTC, Loving11ish commented on src/main/java/me/loving11ish/clans/commands/clanSubCommands/ClanPrefixSubCommand.java
> +                String prefixColorStripped = ChatColor.stripColor(ChatColor.translateAlternateColorCodes('&', prefixRaw));
Does this also check for # RGB & HEX code checking/stripping?

2024-02-12 19:38 UTC, TechnicallyCoded commented
sender.sendMessage() was the original. I didn't change that wasn't related to the goal

2024-02-13 18:28 UTC, Loving11ish commented
> sender.sendMessage() was the original. I didn't change anything that wasn't related to the goal.

Ok fair enough.  How about the other comment?

2024-02-13 22:07 UTC, Loving11ish commented
Now implemented into api dev branch.  Many thanks!

2024-02-13 22:07 UTC, closed without merging